<form action="./" name="reservation-form" method="post" role="form">

    <div class="form-inline">
        <div class="form-group">
            <label class="" for="">First name</label>
            <input type="text" class="form-control" placeholder="" name="res_first_name">
        </div>
        <div class="form-group">
            <label class="" for="">Last name</label>
            <input type="text" class="form-control" placeholder="" name="res_last_name">
        </div>
    </div>
    <div class="form-inline">
        <div class="form-group">
            <label class="" for="">Daytime phone</label>
            <input type="text" class="form-control" placeholder="" name="res_daytime_phone">
        </div>
        <div class="form-group">
            <label class="" for="">Email</label>
            <input type="email" class="form-control" placeholder="" name="res_email">
        </div>
    </div>

    <div class="form-gr"></div>
    <input type="submit" class="btn btn-primary"/>
</form>