<div class="order-complete-details">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <?php echo $title; ?>
            </h3>
        </div>
        <div class="panel-body">
            <p><?php echo $summary; ?></p>
            <div>
                <a href="<?php echo $homepage;?>">
                    <?php echo __('Go to home page')?>
                </a>
            </div>
        </div>
    </div>
</div>